/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Trainma-inspired orange palette
        primary: "#F97316",        // vibrant orange
        "primary-dark": "#EA6C0B",
        "primary-light": "#FED7AA",
        "primary-container": "#FFF7ED",
        cream: "#FAF8F4",
        "cream-dark": "#F5F0E8",
        "on-primary": "#ffffff",
        "on-background": "#1A1A1A",
        "on-surface": "#1A1A1A",
        "on-surface-variant": "#6B7280",
        background: "#FAF8F4",
        surface: "#FAF8F4",
        "surface-container": "#F0EAE0",
        "surface-container-low": "#FFF9F5",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#E5E7EB",
        outline: "#9CA3AF",
        "secondary": "#1A1A1A",
        "on-secondary": "#ffffff",
        error: "#DC2626",
        "error-container": "#FEE2E2",
        "on-error": "#ffffff",
        // status colors
        "success": "#16A34A",
        "warning": "#D97706",
        "info": "#2563EB",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        gutter: "2rem",
        "sidebar-width": "260px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
      },
      fontSize: {
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
