/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#424751',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#737782',
        'outline-variant': '#c2c6d3',
        'surface-tint': '#265ea8',
        primary: '#003e7e',
        'on-primary': '#ffffff',
        'primary-container': '#1a56a0',
        'on-primary-container': '#b3cdff',
        'inverse-primary': '#a9c7ff',
        secondary: '#405f8e',
        'on-secondary': '#ffffff',
        'secondary-container': '#accbff',
        'on-secondary-container': '#365583',
        tertiary: '#34424a',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#4b5962',
        'on-tertiary-container': '#c0cfda',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#a9c7ff',
        'on-primary-fixed': '#001b3d',
        'on-primary-fixed-variant': '#00468c',
        'secondary-fixed': '#d5e3ff',
        'secondary-fixed-dim': '#a9c8fc',
        'on-secondary-fixed': '#001b3c',
        'on-secondary-fixed-variant': '#274774',
        'tertiary-fixed': '#d6e5ef',
        'tertiary-fixed-dim': '#bac9d3',
        'on-tertiary-fixed': '#0f1d25',
        'on-tertiary-fixed-variant': '#3b4951',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        'surface-variant': '#d3e4fe',
        
        // Legacy colors to prevent build errors during transition
        navy: '#213145',
        midBlue: '#1a56a0',
        accentBlue: '#dce9ff',
        lightBlue: '#eff4ff',
        success: '#10B981',
        warning: '#F59E0B',
        danger: '#ba1a1a',
        neutralDark: '#0b1c30',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['Geist', 'monospace'],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      }
    },
  },
  plugins: [],
}
