/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "secondary-fixed-dim": "#a9c8fc",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#274774",
        "primary": "#003e7e",
        "on-background": "#0b1c30",
        "tertiary-fixed": "#d6e5ef",
        "on-surface": "#0b1c30",
        "on-primary-fixed-variant": "#00468c",
        "surface-container-high": "#dce9ff",
        "secondary-fixed": "#d5e3ff",
        "primary-fixed": "#d6e3ff",
        "surface-tint": "#265ea8",
        "on-surface-variant": "#424751",
        "inverse-surface": "#213145",
        "on-secondary-container": "#365583",
        "on-tertiary-container": "#c0cfda",
        "tertiary-container": "#4b5962",
        "primary-container": "#1a56a0",
        "surface-dim": "#cbdbf5",
        "tertiary-fixed-dim": "#bac9d3",
        "on-secondary-fixed": "#001b3c",
        "secondary": "#405f8e",
        "tertiary": "#34424a",
        "on-tertiary-fixed-variant": "#3b4951",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-fixed": "#0f1d25",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001b3d",
        "inverse-primary": "#a9c7ff",
        "surface-container-low": "#eff4ff",
        "surface-variant": "#d3e4fe",
        "on-primary-container": "#b3cdff",
        "primary-fixed-dim": "#a9c7ff",
        "on-secondary": "#ffffff",
        "surface-container": "#e5eeff",
        "background": "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "surface": "#f8f9ff",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "secondary-container": "#accbff",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c2c6d3",
        "outline": "#737782"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "container-max": "1440px",
        "gutter": "1.5rem",
        "sidebar-width": "280px",
        "margin-mobile": "1rem",
        "margin-desktop": "2rem"
      },
      "fontFamily": {
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Geist"],
        "label-md": ["Geist"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"]
      },
      "fontSize": {
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "500"}],
        "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
