import { useState, useEffect, useCallback } from 'react';
import { apiCall } from '../api/client';

interface ImpactMetrics {
  stations_deployed: number;
  track_km_monitored: number;
  avg_delay_saved_min: number;
  passenger_hours_saved_day: number;
  annual_fuel_savings_cr: number;
  animal_lives_saved_yr: number;
  incidents_prevented_yr: number;
}

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const BAR_DATA = [40, 65, 55, 80, 95, 70, 85, 60, 75, 90, 50, 88];

const DEFAULT_METRICS: ImpactMetrics = {
  stations_deployed: 120,
  track_km_monitored: 2500,
  avg_delay_saved_min: 15,
  passenger_hours_saved_day: 14280,
  annual_fuel_savings_cr: 2.4,
  animal_lives_saved_yr: 840,
  incidents_prevented_yr: 1200,
};

function calcLocalMetrics(stations: number, trackKm: number, delaySaved: number): ImpactMetrics {
  return {
    stations_deployed: stations,
    track_km_monitored: trackKm,
    avg_delay_saved_min: delaySaved,
    passenger_hours_saved_day: Math.floor((stations * 100 * delaySaved * 50000) / 60),
    annual_fuel_savings_cr: parseFloat(((100 * delaySaved * 365 * 1000) / 10_000_000).toFixed(2)),
    animal_lives_saved_yr: Math.floor((trackKm / 100) * 2),
    incidents_prevented_yr: Math.floor(stations / 5) * 50,
  };
}

export default function ImpactDashboard() {
  const [stations, setStations] = useState(120);
  const [trackKm, setTrackKm] = useState(2500);
  const [delaySaved, setDelaySaved] = useState(15);
  const [metrics, setMetrics] = useState<ImpactMetrics>(DEFAULT_METRICS);
  const [isCalculating, setIsCalculating] = useState(false);
  const [isLiveData, setIsLiveData] = useState(false);
  const [reportReady, setReportReady] = useState(false);

  const fetchMetrics = useCallback(async (s: number, km: number, d: number) => {
    setIsCalculating(true);
    try {
      const response = await apiCall<ImpactMetrics>(
        `/impact/?stations=${s}&track_km=${km}&delay_saved=${d}`,
        {},
        calcLocalMetrics(s, km, d)
      );
      setMetrics(response);
      // If response values differ significantly from local calc, it's live data
      setIsLiveData(response.stations_deployed !== s);
    } catch {
      setMetrics(calcLocalMetrics(s, km, d));
      setIsLiveData(false);
    } finally {
      setIsCalculating(false);
    }
  }, []);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void fetchMetrics(stations, trackKm, delaySaved);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleRecalculate = () => fetchMetrics(stations, trackKm, delaySaved);

  const handleDownloadReport = () => {
    setReportReady(true);
    const lines = [
      'RAILSENSE AI — AUDIT REPORT',
      `Generated: ${new Date().toLocaleString('en-IN')}`,
      '='.repeat(40),
      '',
      'DEPLOYMENT METRICS',
      `Stations Deployed       : ${metrics.stations_deployed}`,
      `Track km Monitored      : ${metrics.track_km_monitored.toLocaleString()} km`,
      `Avg Delay Saved         : ${metrics.avg_delay_saved_min} min/day`,
      '',
      'IMPACT METRICS (Annual)',
      `Passenger Hrs Saved     : ${metrics.passenger_hours_saved_day.toLocaleString()} hrs/day`,
      `Fuel Cost Savings       : ₹${metrics.annual_fuel_savings_cr} Crore/yr`,
      `Incidents Prevented     : ${metrics.incidents_prevented_yr.toLocaleString()}/yr`,
      `Animal Lives Saved      : ${metrics.animal_lives_saved_yr.toLocaleString()}/yr`,
      '',
      'SYSTEM UPTIME           : 99.8%',
      '',
      'This report is generated by RailSense AI for IRCTC compliance.',
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `railsense_audit_${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    setTimeout(() => setReportReady(false), 2000);
  };

  const kpis = [
    { label: 'Stations Deployed', value: metrics.stations_deployed.toLocaleString(), unit: '', icon: 'location_on', trend: '+12%' },
    { label: 'Track km Monitored', value: metrics.track_km_monitored.toLocaleString(), unit: 'km', icon: 'route', trend: '+8%' },
    { label: 'Delay Saved / Train', value: metrics.avg_delay_saved_min.toLocaleString(), unit: 'min', icon: 'timer', trend: '+5%' },
    { label: 'Passenger Hrs Saved', value: metrics.passenger_hours_saved_day.toLocaleString(), unit: '/day', icon: 'people', trend: '+18%' },
    { label: 'Fuel Savings', value: `₹${metrics.annual_fuel_savings_cr}Cr`, unit: '/yr', icon: 'savings', trend: '+22%' },
    { label: 'Incidents Prevented', value: metrics.incidents_prevented_yr.toLocaleString(), unit: '/yr', icon: 'shield', trend: '+31%' },
    { label: 'Animal Lives Saved', value: metrics.animal_lives_saved_yr.toLocaleString(), unit: '/yr', icon: 'pets', trend: '+7%' },
    { label: 'System Uptime', value: '99.8', unit: '%', icon: 'verified', trend: 'Stable' },
  ];

  const currentMonth = new Date().getMonth();

  return (
    <div className="flex-1 bg-[#FAF8F4] p-6">
      {/* Header */}
      <div className="flex justify-between items-start mb-6 flex-wrap gap-3">
        <div>
          <span className="badge-orange mb-2 inline-block">Analytics</span>
          <h1 className="text-2xl font-black text-gray-900">Impact <span className="text-[#F97316]">Dashboard</span></h1>
          <p className="text-sm text-gray-500 mt-1">Live KPIs from RailSense AI deployment across Indian Railways</p>
        </div>
        <div className="flex items-center gap-3">
          <span className={`text-[10px] font-bold px-2 py-1 rounded-full ${isLiveData ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700'}`}>
            {isLiveData ? '● Live DB Data' : '● Calculated'}
          </span>
          <button
            onClick={handleRecalculate}
            disabled={isCalculating}
            className="orange-btn flex items-center gap-2 text-sm"
          >
            <span className={`material-symbols-outlined text-[18px] ${isCalculating ? 'animate-spin' : ''}`}>refresh</span>
            {isCalculating ? 'Calculating…' : 'Recalculate'}
          </button>
        </div>
      </div>

      {/* Parameter sliders */}
      <div className="card p-5 mb-6 grid grid-cols-1 md:grid-cols-3 gap-5">
        <h3 className="col-span-full font-bold text-gray-900 text-sm -mb-2">Simulation Parameters</h3>
        {[
          { label: 'Stations Deployed', value: stations, setter: setStations, min: 1, max: 500 },
          { label: 'Track km Monitored', value: trackKm, setter: setTrackKm, min: 100, max: 10000 },
          { label: 'Avg Delay Saved (min)', value: delaySaved, setter: setDelaySaved, min: 1, max: 60 },
        ].map(c => (
          <div key={c.label}>
            <div className="flex justify-between mb-1">
              <label className="text-xs font-semibold text-gray-500">{c.label}</label>
              <span className="text-xs font-bold text-[#F97316]">{c.value.toLocaleString()}</span>
            </div>
            <input
              type="range"
              min={c.min}
              max={c.max}
              value={c.value}
              onChange={e => c.setter(Number(e.target.value))}
              className="w-full accent-[#F97316] h-2 rounded"
            />
            <div className="flex justify-between text-[9px] text-gray-400 mt-0.5">
              <span>{c.min.toLocaleString()}</span>
              <span>{c.max.toLocaleString()}</span>
            </div>
          </div>
        ))}
      </div>

      {/* KPI grid */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        {kpis.map(k => (
          <div key={k.label} className="card p-4 card-hover">
            <div className="flex items-start justify-between mb-3">
              <div className="w-9 h-9 bg-[#FFF7ED] rounded-xl flex items-center justify-center">
                <span className="material-symbols-outlined text-[#F97316] text-[18px]" style={{ fontVariationSettings: "'FILL' 1" }}>{k.icon}</span>
              </div>
              <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded ${k.trend === 'Stable' ? 'bg-blue-50 text-blue-600' : 'bg-green-50 text-green-700'}`}>
                {k.trend}
              </span>
            </div>
            <p className="font-black text-xl text-gray-900">
              {k.value}
              {k.unit && <span className="text-sm text-gray-400 font-normal ml-1">{k.unit}</span>}
            </p>
            <p className="text-xs text-gray-500 mt-1">{k.label}</p>
          </div>
        ))}
      </div>

      {/* Monthly performance chart */}
      <div className="card p-5 mb-6">
        <div className="flex justify-between items-center mb-5">
          <div>
            <h3 className="font-bold text-gray-900">Monthly Performance</h3>
            <p className="text-xs text-gray-400 mt-0.5">Incidents prevented per month · {new Date().getFullYear()}</p>
          </div>
          <div className="flex gap-3 text-xs">
            <span className="flex items-center gap-1">
              <span className="w-3 h-3 rounded-sm bg-[#F97316] inline-block"></span>Current Month
            </span>
            <span className="flex items-center gap-1">
              <span className="w-3 h-3 rounded-sm bg-[#FED7AA] inline-block"></span>Other Months
            </span>
          </div>
        </div>
        <div className="flex items-end gap-1.5 h-36">
          {BAR_DATA.map((h, i) => (
            <div key={i} className="flex-1 flex flex-col items-center gap-1 group">
              <div
                className="w-full rounded-t-sm transition-all hover:opacity-90 cursor-pointer"
                title={`${MONTHS[i]}: ${Math.floor(h * metrics.incidents_prevented_yr / 1200)} incidents`}
                style={{ height: `${h * 1.3}px`, background: i === currentMonth ? '#F97316' : '#FED7AA' }}
              ></div>
              <span className="text-[9px] text-gray-400">{MONTHS[i]}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Bottom grid */}
      <div className="grid grid-cols-2 gap-5">
        {/* Feature breakdown */}
        <div className="card p-5">
          <h3 className="font-bold text-gray-900 mb-4">Feature Adoption</h3>
          {[
            { label: 'Delay Predictor', pct: 94, color: '#F97316' },
            { label: 'Platform Guard', pct: 87, color: '#EA580C' },
            { label: 'Track Inspector', pct: 76, color: '#C2410C' },
            { label: 'Citizen App', pct: 62, color: '#9A3412' },
          ].map(f => (
            <div key={f.label} className="mb-4">
              <div className="flex justify-between mb-1.5">
                <span className="text-xs font-semibold text-gray-700">{f.label}</span>
                <span className="text-xs font-bold" style={{ color: f.color }}>{f.pct}%</span>
              </div>
              <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                <div
                  className="h-full rounded-full transition-all duration-700"
                  style={{ width: `${f.pct}%`, background: f.color }}
                ></div>
              </div>
            </div>
          ))}

          {/* Mini donut summary */}
          <div className="mt-5 pt-4 border-t border-gray-100">
            <p className="text-xs text-gray-400 font-semibold mb-2">Overall System Efficiency</p>
            <div className="flex items-center gap-3">
              <div className="relative w-14 h-14">
                <svg className="w-full h-full -rotate-90" viewBox="0 0 56 56">
                  <circle cx="28" cy="28" r="22" fill="transparent" stroke="#FED7AA" strokeWidth="6"/>
                  <circle cx="28" cy="28" r="22" fill="transparent" stroke="#F97316" strokeWidth="6"
                    strokeDasharray="138"
                    strokeDashoffset={138 - (138 * 0.888)}/>
                </svg>
                <div className="absolute inset-0 flex items-center justify-center">
                  <span className="font-black text-xs text-gray-900">88%</span>
                </div>
              </div>
              <div>
                <p className="font-bold text-sm text-gray-800">88.8% efficient</p>
                <p className="text-xs text-gray-400">Across all modules</p>
              </div>
            </div>
          </div>
        </div>

        {/* Audit report card */}
        <div className="bg-[#F97316] rounded-2xl p-6 text-white flex flex-col">
          <h3 className="font-bold text-lg mb-1">Generate Audit Report</h3>
          <p className="text-white/70 text-sm mb-5">Full compliance report for IRCTC submission with all KPIs.</p>
          <div className="space-y-2 mb-5 flex-1">
            {[
              'Safety incidents prevented',
              'Fuel cost savings analysis',
              'Track defect summary',
              'Passenger hours saved',
              'System uptime & reliability',
              'Cascade impact analysis',
            ].map(item => (
              <div key={item} className="flex items-center gap-2 text-sm text-white/90">
                <span className="material-symbols-outlined text-[14px]" style={{ fontVariationSettings: "'FILL' 1" }}>check_circle</span>
                {item}
              </div>
            ))}
          </div>

          {/* Summary numbers */}
          <div className="grid grid-cols-2 gap-2 mb-5">
            {[
              { label: 'Fuel Saved', value: `₹${metrics.annual_fuel_savings_cr}Cr` },
              { label: 'Incidents', value: metrics.incidents_prevented_yr.toLocaleString() },
            ].map(s => (
              <div key={s.label} className="bg-white/20 rounded-xl p-3 text-center">
                <p className="font-black text-lg">{s.value}</p>
                <p className="text-white/70 text-[10px]">{s.label}</p>
              </div>
            ))}
          </div>

          <button
            onClick={handleDownloadReport}
            className="w-full py-2.5 bg-white text-[#F97316] font-bold rounded-xl text-sm hover:bg-orange-50 transition-colors flex items-center justify-center gap-2"
          >
            <span className="material-symbols-outlined text-[16px]">{reportReady ? 'check' : 'download'}</span>
            {reportReady ? 'Report Downloaded!' : 'Download Report'}
          </button>
        </div>
      </div>
    </div>
  );
}
